stages:
  - build
  - package
  - deploy
  
before_script:
    - "npm install"

android-build:
  stage: build
  script: "npm run android:build"
  artifacts:
    paths:
      - android/app/build/outputs/apks/*.zip