stages:
  - build
  - package
  - deploy
  
before_script:
   - sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
   - npm install

android-build:
  stage: build
  script: 
    - "npm run android:build"
  artifacts:
    paths:
      - android/app/build/outputs/apks/*.zip