stages:
  - build
  - package
  - deploy
  
before_script:
   - export PATH=/root/.nvm/versions/node/v8.5.0/bin
   - sudo chown -R $(whoami) $(/root/.nvm/versions/node/v8.5.0)/{lib/node_modules,bin,share}
   - npm install

android-build:
  stage: build
  script: 
    - "npm run android:build"
  artifacts:
    paths:
      - android/app/build/outputs/apks/*.zip