stages:
  - build
  - package
  - deploy
  
before_script:
   

android-build:
  stage: build
  script: 
    - "npm install"
    - "npm run android:build"
  artifacts:
    paths:
      - android/app/build/outputs/apks/*.zip