language: android
before_install:
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- cd android && ./gradlew assembleRelease
deploy:
  skip_cleanup: 'true'
  provider: releases
  api_key:
    secure: AAKY74JdIJw2MDz1cBiXQwkUGzlD8v9DmDGtKXb6Xi0/p2BkAwxVBZ2VQuPhaT5vGcImTZg/o0mK/42KK35mKBvh4xrOgzvTKuD5Thmy2MCS21fRenZoZdjqtrqpJT/e0I2YzHre03fTOhUz4ng6c1n2K58hoz1ABdeD+jZaRXTz5Q+754ULJvcE2CNzjIM5j/x+sOmMkbj6KNA0Tul7pmQ5zCivN+upCAxodabnU4ank2ONm+rMN5iMsAiRPQRhfq4K/pQAEbzQlQfZUMEXO7oXaeiee3Fjh9NvhtFvbxHdgYbXZZoOAD+/LnO9/lkS38WunnF9GtiXAh05J0sacG6/uM1FBUQiaV9hfywitOo0EAXhuOo2JsVLsxJh4VjIkLFutgu9q4e1DWg7XzZ6MMmX9vjsblxBMUCP+OBd8NBHfOnebO6cvnn8ZpsleJc+kS27xXgocFCQr00EZbL1tliFNpJZFyZAmSVmktXkbIsLdCAnkoGuWdXaVOb6y2NMQMgjbNx9nzj1vZUclaEC/nZm2T+o5daXH4dUs84NigZjUlnZ09l1q10WG3RlhpfhA7Yj0IhAwasR74yR1OEKMgjwtnvBFKMQHMxM2hEm7gcInIX7IRIccslCc+wA9M4yWW08SkJnH4OInPkwHtBha/moyOEFz7A8IZDfNVg8gFY=
  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app*release*.apk
  file_glob: 'true'
  on:
    repo: samuraitruong/react-native-fx260
    branch: master
  after_success:
  - sh set_tags.sh
  provider: bintray
    file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app*release*.apk
    user: "samuraitruong"
    key:
      secure: O+yLOLFYonGwmIvqrYHrqNvZTvLnvnKR9kMF9vWmz4FzPdXVYtYW96jTp9BKsOZla4gJucVgztm2Heq1LIGummv0E8H3cQOpgQAGWZqYHqmGgD3CESN/Cs0h74aaGJbMW1oi6h7+apszUKDeaJuxq3oLMK9lRRpygkB8WH1GKKQcJavugsg7DFaq8t/3I05m47Yrfkbsz1rIzRw+Glyg8qR4nkbM9LvjrkVx/3XYiAsCSKKM3Z1s2PZrupSDVBjSblhfDvyFAgrfhs0rmFf7djPeZy7TvQb4ZvGVCgJOjVWiHbzf3HyMgcZ2IzNoXBmfiDJrgYn4YiW5AjakPhynsQXlvHBUdBXwrqGeC6YDXBlBT67z8i71Z57BPmq9+fDbvYSLUgOD5cTOK9Fu59syiAF4Ga8Nj/jeVZYcvn7H7Zdqmk0Iuy0YqlJBusBBK7sD/RJUOWM3zxx2KJAx6LPDqEX7NUBz99fmAY2H9GZvrM9sFtzFmMDqb52i4xtKJ0667iZUy1WsCB3ugzvrJPL+mo49ZJuSY/+mTmmBjR3C/zqL++82Kv7HFTIiId7HBzSsXsBOsIipgeV7uV7OQxM02z0bEzj0SXHYGAsEgwJ5a/EBXppBTdMYtWZjrxaBb8KVFxYOYZZffgmCY4cQ7hvfitHSLoSwpdQ15JFrd22NVk0=
    on:
    repo: samuraitruong/react-native-fx260
    all_branches: true
